//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> DistributedAt { get; set; }
        public int PeopleFed { get; set; }
        public string Status { get; set; }
    
        public virtual CollectionRequest CollectionRequest { get; set; }
        public virtual User User { get; set; }
    }
}
